language: python
os: linux
services:
  - docker
dist: xenial          # required for Python >= 3.7

before_script:
  - sudo apt purge docker-ce
  - curl -fsSL https://get.docker.com/ -o docker-install.sh
  - CHANNEL=nightly sh docker-install.sh
  - sudo docker run --privileged linuxkit/binfmt:v0.7
  - docker buildx create --name mybuilder
  - docker buildx use mybuilder
  - docker buildx inspect --bootstrap
  - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

install: 
  - pip install --upgrade pip 

matrix:
  include:
    - stage: lint
      python: 3.7
      name: 'lint'
      script: 
        - pip install .
        - pip install pylint
        - pylint -rn --errors-only ./magic
    
    - stage: test
      python: 3.7
      name: 'test python 3'
      script:      
        - pip install .
        - pip install coveralls
        - rm -r tests/radius
        - coverage run --source magic -m py.test
        - coveralls
      
    - script:
        - pip install future hjson pytest
        - rm -r tests/agent
        - cp -r magic/radius/ tests/radius/
        - cp magic/utils/authobject.py tests/radius/authobject.py
        - cp magic/utils/configloader.py tests/radius/configloader.py
        - py.test tests/radius/
      name: 'test python 2'
      python: 2.7

    - stage: prepare
      if: branch = master && "$TRAVIS_PULL_REQUEST" == "false"
      name: 'build agent base image'
      script:         
        - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --file ./scripts/docker/Dockerfile.agent.base -t $DOCKERHUB_REPO:agent-base . --push

    - stage: deploy
      if: branch = master && "$TRAVIS_PULL_REQUEST" == "false"
      name: 'deploy gateway'
      script:
        - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --file ./scripts/docker/Dockerfile.agent.derived --build-arg DOCKERHUB_REPO=$DOCKERHUB_REPO -t $DOCKERHUB_REPO:gateway . --push
      
    - script:
        - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --file ./scripts/docker/Dockerfile.agent.derived --build-arg DOCKERHUB_REPO=$DOCKERHUB_REPO --build-arg AGENT_TYPE=payment -t $DOCKERHUB_REPO:payments . --push
      name: 'deploy payments'
      if: branch = master && "$TRAVIS_PULL_REQUEST" == "false"

      # Right now there is no ARM images on dockerhub for freeradius
    - script:
        - docker buildx build --platform linux/amd64 --file Dockerfile.radius -t $DOCKERHUB_REPO:radius . --push
      name: 'deploy radius'
      if: branch = master && "$TRAVIS_PULL_REQUEST" == "false"

    - script:
        - docker buildx build --platform linux/amd64 --file ./scripts/docker/Dockerfile.alpine.radius -t $DOCKERHUB_REPO:radius-alpine . --push
      name: 'deploy alpine radius'
      if: branch = master && "$TRAVIS_PULL_REQUEST" == "false"

# deploy only works for travis supported providers which dockerhub is not one of
#deploy:

env:
  global:
    - DOCKER_BUILDKIT=1
    - DOCKER_CLI_EXPERIMENTAL=enabled