FROM python:3.7-slim

RUN apt-get update && apt-get install -y \
	build-essential automake pkg-config \
	libtool libffi-dev libssl-dev supervisor

# Set the install location for the agent
ARG MAGIC_LOC=/usr/app/agent
ENV MAGIC_LOC ${MAGIC_LOC}
WORKDIR ${MAGIC_LOC}

# Set the agent type
ARG AGENT_TYPE=gateway
ENV AGENT_TYPE ${AGENT_TYPE}

# Copy all the files we actually need to run the agents
COPY magic magic
COPY requirements.txt .
COPY setup.py .
COPY version.txt .
COPY MANIFEST.in .
COPY conf/user-config.hjson magic/${AGENT_TYPE}

# Install, note the when this installs it installs it to the python dist-packages
# thats why we need the manifest
RUN pip3 install .

RUN pip3 install pylint
