version: '3'

services:
  magic-gateway:
    build: .
    image: magicnetwork/magic-agent
    network_mode: "host"
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
      - "5000:5000"
    environment:
      - ADMIN_ROUTER_ADDRESS=192.168.1.1
      - ADMIN_RADIUS_SECRET=magicsecret
    command: ["/run.sh", "gateway", "start"]
#  magic-payment-enabler:
#    build: .
#    image: magicnetwork/magic-agent
#    network_mode: "host"
#    ports:
#    - "8080:5000"
#    command: ["/run.sh", "payment", "start"]
