FROM ubuntu:bionic

RUN apt-get update && \
    apt-get install -yy \
        python3 \
        python3-pip \
	libssl-dev \
	libgmp3-dev \
	libffi6 \
	libffi-dev \
	libtool \
	autoconf \
	pkg-config \
	dos2unix

# Set the install location for the agent
ARG MAGIC_LOC=/usr/app/agent
ENV MAGIC_LOC ${MAGIC_LOC}
WORKDIR ${MAGIC_LOC}

# Copy all the files we actually need to run the agents
COPY magic magic
COPY requirements.txt .
COPY setup.py .
COPY version.txt .
COPY MANIFEST.in .
COPY conf/user-config.hjson magic/gateway/config

# Install, note the when this installs it installs it to the python dist-packages
# thats why we need the manifest
RUN pip3 install .

COPY run.sh /run.sh
# Make sure it has unix line endings and no permission issues
RUN dos2unix /run.sh
RUN chmod 777 /run.sh

EXPOSE 5000/tcp

# Add Tini
ARG TINI_VERSION=v0.18.0
ARG ARCH=amd64
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${ARCH} /tini
RUN chmod +x /tini

ENTRYPOINT ["/tini", "--"]
CMD ["/run.sh", "gateway", "start"] # Set default command
