version: '3'

services:
  freeradius:
    build: 
      context: .
      dockerfile: Dockerfile.radius
      args:
        MAGIC_LOC: /usr/app/agent
    image: magicnetwork/magic-agent:radius
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    environment:
      - ADMIN_ROUTER_ADDRESS=192.168.1.1
      - ADMIN_RADIUS_SECRET=magicsecret
      - MAGIC_PORT=12345
      - GATEWAY_LOC=gateway
  gateway:
    build: 
      context: .
      dockerfile: Dockerfile.agent
      args:
        MAGIC_LOC: /usr/app/agent
        AGENT_TYPE: gateway
    image: magicnetwork/magic-agent:gateway
    ports:
      - "5000:5000"
    environment:
      - MAGIC_PORT=12345
  payments:
    build: 
      context: .
      dockerfile: Dockerfile.agent
      args:
        MAGIC_LOC: /usr/app/agent
        AGENT_TYPE: payment
    image: magicnetwork/magic-agent:payments
    ports:
      - "8080:5001"
    environment:
        - PYTHONUNBUFFERED=1
      # - ADMIN_ETH_ADDRESS=0x00
      # - ADMIN_ETH_PRIVATE_KEY=0x00
