FROM python:3.7-slim

RUN apt-get update && apt-get install -y \
	build-essential automake pkg-config \
	libtool libffi-dev libssl-dev supervisor

# Set the repo location
ARG DOCKERHUB_REPO=magicnetwork/magic-agent
ENV DOCKERHUB_REPO ${DOCKERHUB_REPO}

# Set the install location for the agent
ARG MAGIC_LOC=/usr/app/agent
ENV MAGIC_LOC ${MAGIC_LOC}
WORKDIR ${MAGIC_LOC}

# Copy all the files we actually need to run the agents
COPY magic magic
COPY requirements.txt .
COPY setup.py .
COPY version.txt .
COPY MANIFEST.in .

# Install, note the when this installs it installs it to the python dist-packages
# thats why we need the manifest
RUN pip3 install .

